FROM python:3.13-slim

LABEL authors="AFMac"

WORKDIR /app
COPY "requirements.txt" ./

RUN pip install --ignore-installed -r requirements.txt

COPY "predict.py" "xgboost_model.bin" ./

EXPOSE 9696

ENTRYPOINT ["waitress-serve", "--listen=0.0.0.0:9696", "predict:app"]
